version: '3.7'

services:
  backend:
    build: .
    image: ganeshraja10/sample-backend:${BUILD_NUMBER}
    ports:
      - '3000:3000'
    restart: on-failure
    networks:
      - backend

networks:
  backend:
